// LAST HUNT: KILLBOX - Props Configuration
// Defines rocks, logs, stumps, root clusters, and other level objects

export const PROP_TYPES = {
  SMALL_ROCK: 'small_rock',
  MEDIUM_ROCK: 'medium_rock',
  LARGE_BOULDER: 'large_boulder',
  HOLLOW_LOG: 'hollow_log',
  FALLEN_LOG: 'fallen_log',
  STUMP: 'stump',
  ROOT_CLUSTER: 'root_cluster',
  FALLEN_BRANCH: 'fallen_branch',
};

export const ROCK_PHYSICS = {
  small_rock: {
    movable: true,
    mass: 1,
    explosionForceMultiplier: 1.4,
    friction: 0.92,
    bounce: 0.25,
    crushDamage: 15,
    minSpeedForDamage: 3,
  },
  medium_rock: {
    movable: true,
    mass: 3,
    explosionForceMultiplier: 0.75,
    friction: 0.95,
    bounce: 0.15,
    crushDamage: 35,
    minSpeedForDamage: 2,
  },
  large_boulder: {
    movable: true,
    mass: 7,
    explosionForceMultiplier: 0.35,
    friction: 0.97,
    bounce: 0.05,
    crushDamage: 70,
    minSpeedForDamage: 1.5,
  },
};

export const PROP_CONFIG = {
  [PROP_TYPES.SMALL_ROCK]: {
    health: 8,
    w: 16, h: 14,
    destructible: true,
    flammable: false,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 5,
    yields: { stone: 0.3 },
    hitFx: 'stone_chip',
    destroyFx: 'rock_shatter_small',
    movable: true,
    physics: ROCK_PHYSICS.small_rock,
  },
  [PROP_TYPES.MEDIUM_ROCK]: {
    health: 20,
    w: 28, h: 22,
    destructible: true,
    flammable: false,
    blocksMovement: true,
    blocksBullets: true,
    damageThreshold: 10,
    yields: { stone: 0.8 },
    needsExplosion: true,  // heavy weapons only
    hitFx: 'stone_chip_medium',
    destroyFx: 'rock_shatter_medium',
    movable: true,
    physics: ROCK_PHYSICS.medium_rock,
  },
  [PROP_TYPES.LARGE_BOULDER]: {
    health: 60,
    w: 48, h: 38,
    destructible: true,
    flammable: false,
    blocksMovement: true,
    blocksBullets: true,
    damageThreshold: 25,
    yields: { stone: 2.0 },
    needsExplosion: true,
    heavyObject: true,  // can be moved by explosions
    hitFx: 'stone_chip_heavy',
    destroyFx: 'boulder_explode',
    movable: true,
    physics: ROCK_PHYSICS.large_boulder,
  },
  [PROP_TYPES.HOLLOW_LOG]: {
    health: 15,
    w: 40, h: 16,
    destructible: true,
    flammable: true,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 5,
    climbable: true,  // can crawl through
    yields: { wood: 0.7 },
    hitFx: 'wood_thunk',
    destroyFx: 'log_shatter',
  },
  [PROP_TYPES.FALLEN_LOG]: {
    health: 25,
    w: 50, h: 12,
    destructible: true,
    flammable: true,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 8,
    climbable: true,
    yields: { wood: 1.2 },
    hitFx: 'wood_thunk',
    destroyFx: 'log_break',
  },
  [PROP_TYPES.STUMP]: {
    health: 30,
    w: 18, h: 16,
    destructible: true,
    flammable: true,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 10,
    yields: { wood: 0.8 },
    hitFx: 'wood_chunk',
    destroyFx: 'stump_explode',
  },
  [PROP_TYPES.ROOT_CLUSTER]: {
    health: 12,
    w: 24, h: 18,
    destructible: true,
    flammable: false,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 5,
    yields: { wood: 0.4 },
    hitFx: 'root_crack',
    destroyFx: 'root_scatter',
  },
  [PROP_TYPES.FALLEN_BRANCH]: {
    health: 5,
    w: 32, h: 8,
    destructible: true,
    flammable: true,
    blocksMovement: false,
    blocksBullets: false,
    damageThreshold: 2,
    climbable: true,
    yields: { wood: 0.2 },
    hitFx: 'branch_crack',
    destroyFx: 'branch_splinter',
  },
};

export const BIOME_PROP_DENSITY = {
  JUNGLE: {
    smallRockDensity: 0.15,
    mediumRockDensity: 0.08,
    boulderDensity: 0.03,
    logDensity: 0.1,
    stumpDensity: 0.05,
    rootDensity: 0.12,
  },
  SWAMP: {
    smallRockDensity: 0.05,
    mediumRockDensity: 0.02,
    boulderDensity: 0.01,
    logDensity: 0.15,
    stumpDensity: 0.08,
    rootDensity: 0.18,
  },
  ROCKY_TERRAIN: {
    smallRockDensity: 0.3,
    mediumRockDensity: 0.15,
    boulderDensity: 0.06,
    logDensity: 0.05,
    stumpDensity: 0.02,
    rootDensity: 0.05,
  },
};